### ISSUE TITLE
Questions about environment of KE

### ISSUE THREAD

**Issue by yaohui120** [VLKEB/VLKEB#5]
I installed the transformers 4.1 (same as requirement.txt), but it appears that ''ImportError: cannot import name 'LlamaTokenizer' from 'transformers''. Did you have this question before?

**Comment by hanhuang22** [comment]
Hi, the environments are [here](https://github.com/VLKEB/VLKEB/tree/main/envs). You may check the versions of packages or create new environments with conda from these files. The versions: transformers==4.38 (or transformers==4.28.0 in ke), allennlp==2.8.0. You may install allennlp manually if encounter package dependency resolution issues.

**Comment by kailinjiang** [comment]
When we were configuring the KE environment, we found that many packages conflicted. Could you please provide a file with the following installation form? Thank you!
conda create -n vlkeb python=3.11
pip install -r xxx.txt

**Comment by hanhuang22** [comment]
hi, I add a minimal requirements for KE ([here](https://github.com/VLKEB/VLKEB/blob/main/envs/ke_requirements.txt)), which only contains necessary packages. You may use this or adjust the versions of these packages to adapt to your development environment.
