### ISSUE TITLE
On September 6, the code was updated, unable to run models other than blip2

### ISSUE THREAD

**Issue by kailinjiang** [VLKEB/VLKEB#6]
When running models such as llava, you will encounter code errors
TypeError: LlamaDecoderLayer.__init__() takes 2 positional arguments but 3 were given
![fed990750e5c2d87907f2940adeef63](https://github.com/user-attachments/assets/c8aed3a5-3f7f-4289-81c2-479f4da02608)

**Comment by JZSAWYER** [comment]
> When running models such as llava, you will encounter code errors TypeError: LlamaDecoderLayer.**init**() takes 2 positional arguments but 3 were given ![fed990750e5c2d87907f2940adeef63](https://private-user-images.githubusercontent.com/147908634/366711992-c8aed3a5-3f7f-4289-81c2-479f4da02608.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMTUwMDAsIm5iZiI6MTcyNjMxNDcwMCwicGF0aCI6Ii8xNDc5MDg2MzQvMzY2NzExOTkyLWM4YWVkM2E1LTNmN2YtNDI4OS04MWMyLTQ3OWY0ZGEwMjYwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQxMTUxNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOGMyYmNkMWRlZjNjMDE0NGUxOWU3YTQxMDA4NTcxMjhkZGU1MjU3YzZiNDM1ZjIyZGViOGVkZDRhN2VlMWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vSMiDydnNbGHZ57YQzdXQrmjY0dL04Cu-e3ADB3SDUA)

hi kailin, I have updated the repo to fix the bug

**Comment by kailinjiang** [comment]
Thank you for your work!

**Comment by kailinjiang** [comment]
Thank you for your work!
