### ISSUE TITLE
port['inputs'] in coco_caption.py acts as a consultation

### ISSUE THREAD

**Issue by kailinjiang** [VLKEB/VLKEB#7]
![ea8b59a54aa3070e1f1140ef8f762ae](https://github.com/user-attachments/assets/58309ea2-c8f2-49dd-8f20-9a828928f23b)

port['inputs'] = self.tok(f'Picture 1:  <img>{image[0]}</img>\n{port_q[0]} {port_a[0]}', return_tensors='pt')["input_ids"]
What does this field do? port_a[0] and port_q[0] take out the first letter.

**Comment by JZSAWYER** [comment]
hi kailin, i have updated the repoto fix the bug

**Comment by kailinjiang** [comment]
Thank you for your work!
