### ISSUE TITLE
AttributeError: 'MPLUGOwl2Config' object has no attribute 'attention_dropout'

### ISSUE THREAD

**Issue by kailinjiang** [VLKEB/VLKEB#9]
AttributeError: 'MPLUGOwl2Config' object has no attribute 'attention_dropout'

**Comment by JZSAWYER** [comment]
Hi Kailin,
I have updated the necessary environment for running the Owl2 model code. The new environment is at [vlkeb_owl2](https://github.com/VLKEB/VLKEB/blob/main/envs/vlkeb_owl2.yml). Thank you for your kind reminder!

**Comment by kailinjiang** [comment]
Thank you for your work!
